wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1665700619.06437
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.10.4
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
